version: '2.0'

services:
  sudoku:
    container_name: sudoku
    hostname: sudoku
    build:
      context: .
      dockerfile: Dockerfile
    image: sudoku:dev
    restart: always
    tty: true
    volumes:
      - .:/sudoku
